using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SmartCBSDataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblBillChargingMode class.
	/// </summary>
    [Serializable]
	public partial class TblBillChargingModeCollection : ActiveList<TblBillChargingMode, TblBillChargingModeCollection>
	{	   
		public TblBillChargingModeCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblBillChargingModeCollection</returns>
		public TblBillChargingModeCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblBillChargingMode o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblBillChargingMode table.
	/// </summary>
	[Serializable]
	public partial class TblBillChargingMode : ActiveRecord<TblBillChargingMode>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblBillChargingMode()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblBillChargingMode(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblBillChargingMode(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblBillChargingMode(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblBillChargingMode", TableType.Table, DataService.GetInstance("PrimaryProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarBillChargingModeID = new TableSchema.TableColumn(schema);
				colvarBillChargingModeID.ColumnName = "BillChargingModeID";
				colvarBillChargingModeID.DataType = DbType.Int32;
				colvarBillChargingModeID.MaxLength = 0;
				colvarBillChargingModeID.AutoIncrement = true;
				colvarBillChargingModeID.IsNullable = false;
				colvarBillChargingModeID.IsPrimaryKey = true;
				colvarBillChargingModeID.IsForeignKey = false;
				colvarBillChargingModeID.IsReadOnly = false;
				colvarBillChargingModeID.DefaultSetting = @"";
				colvarBillChargingModeID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBillChargingModeID);
				
				TableSchema.TableColumn colvarBillChargingModeName = new TableSchema.TableColumn(schema);
				colvarBillChargingModeName.ColumnName = "BillChargingModeName";
				colvarBillChargingModeName.DataType = DbType.AnsiString;
				colvarBillChargingModeName.MaxLength = 50;
				colvarBillChargingModeName.AutoIncrement = false;
				colvarBillChargingModeName.IsNullable = true;
				colvarBillChargingModeName.IsPrimaryKey = false;
				colvarBillChargingModeName.IsForeignKey = false;
				colvarBillChargingModeName.IsReadOnly = false;
				colvarBillChargingModeName.DefaultSetting = @"";
				colvarBillChargingModeName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBillChargingModeName);
				
				TableSchema.TableColumn colvarBillChargingModeCode = new TableSchema.TableColumn(schema);
				colvarBillChargingModeCode.ColumnName = "BillChargingModeCode";
				colvarBillChargingModeCode.DataType = DbType.AnsiString;
				colvarBillChargingModeCode.MaxLength = 50;
				colvarBillChargingModeCode.AutoIncrement = false;
				colvarBillChargingModeCode.IsNullable = true;
				colvarBillChargingModeCode.IsPrimaryKey = false;
				colvarBillChargingModeCode.IsForeignKey = false;
				colvarBillChargingModeCode.IsReadOnly = false;
				colvarBillChargingModeCode.DefaultSetting = @"";
				colvarBillChargingModeCode.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBillChargingModeCode);
				
				TableSchema.TableColumn colvarIsActive = new TableSchema.TableColumn(schema);
				colvarIsActive.ColumnName = "IsActive";
				colvarIsActive.DataType = DbType.Boolean;
				colvarIsActive.MaxLength = 0;
				colvarIsActive.AutoIncrement = false;
				colvarIsActive.IsNullable = true;
				colvarIsActive.IsPrimaryKey = false;
				colvarIsActive.IsForeignKey = false;
				colvarIsActive.IsReadOnly = false;
				colvarIsActive.DefaultSetting = @"";
				colvarIsActive.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIsActive);
				
				TableSchema.TableColumn colvarCreatedOn = new TableSchema.TableColumn(schema);
				colvarCreatedOn.ColumnName = "CreatedOn";
				colvarCreatedOn.DataType = DbType.DateTime;
				colvarCreatedOn.MaxLength = 0;
				colvarCreatedOn.AutoIncrement = false;
				colvarCreatedOn.IsNullable = true;
				colvarCreatedOn.IsPrimaryKey = false;
				colvarCreatedOn.IsForeignKey = false;
				colvarCreatedOn.IsReadOnly = false;
				colvarCreatedOn.DefaultSetting = @"";
				colvarCreatedOn.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCreatedOn);
				
				TableSchema.TableColumn colvarModifiedOn = new TableSchema.TableColumn(schema);
				colvarModifiedOn.ColumnName = "ModifiedOn";
				colvarModifiedOn.DataType = DbType.DateTime;
				colvarModifiedOn.MaxLength = 0;
				colvarModifiedOn.AutoIncrement = false;
				colvarModifiedOn.IsNullable = true;
				colvarModifiedOn.IsPrimaryKey = false;
				colvarModifiedOn.IsForeignKey = false;
				colvarModifiedOn.IsReadOnly = false;
				colvarModifiedOn.DefaultSetting = @"";
				colvarModifiedOn.ForeignKeyTableName = "";
				schema.Columns.Add(colvarModifiedOn);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["PrimaryProvider"].AddSchema("TblBillChargingMode",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("BillChargingModeID")]
		[Bindable(true)]
		public int BillChargingModeID 
		{
			get { return GetColumnValue<int>(Columns.BillChargingModeID); }
			set { SetColumnValue(Columns.BillChargingModeID, value); }
		}
		  
		[XmlAttribute("BillChargingModeName")]
		[Bindable(true)]
		public string BillChargingModeName 
		{
			get { return GetColumnValue<string>(Columns.BillChargingModeName); }
			set { SetColumnValue(Columns.BillChargingModeName, value); }
		}
		  
		[XmlAttribute("BillChargingModeCode")]
		[Bindable(true)]
		public string BillChargingModeCode 
		{
			get { return GetColumnValue<string>(Columns.BillChargingModeCode); }
			set { SetColumnValue(Columns.BillChargingModeCode, value); }
		}
		  
		[XmlAttribute("IsActive")]
		[Bindable(true)]
		public bool? IsActive 
		{
			get { return GetColumnValue<bool?>(Columns.IsActive); }
			set { SetColumnValue(Columns.IsActive, value); }
		}
		  
		[XmlAttribute("CreatedOn")]
		[Bindable(true)]
		public DateTime? CreatedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.CreatedOn); }
			set { SetColumnValue(Columns.CreatedOn, value); }
		}
		  
		[XmlAttribute("ModifiedOn")]
		[Bindable(true)]
		public DateTime? ModifiedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.ModifiedOn); }
			set { SetColumnValue(Columns.ModifiedOn, value); }
		}
		
		#endregion
		
		
		#region PrimaryKey Methods		
		
        protected override void SetPrimaryKey(object oValue)
        {
            base.SetPrimaryKey(oValue);
            
            SetPKValues();
        }
        
		
		public SmartCBSDataAccess.TblBillCollection TblBillRecords()
		{
			return new SmartCBSDataAccess.TblBillCollection().Where(TblBill.Columns.BillChargingModeID, BillChargingModeID).Load();
		}
		#endregion
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varBillChargingModeName,string varBillChargingModeCode,bool? varIsActive,DateTime? varCreatedOn,DateTime? varModifiedOn)
		{
			TblBillChargingMode item = new TblBillChargingMode();
			
			item.BillChargingModeName = varBillChargingModeName;
			
			item.BillChargingModeCode = varBillChargingModeCode;
			
			item.IsActive = varIsActive;
			
			item.CreatedOn = varCreatedOn;
			
			item.ModifiedOn = varModifiedOn;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varBillChargingModeID,string varBillChargingModeName,string varBillChargingModeCode,bool? varIsActive,DateTime? varCreatedOn,DateTime? varModifiedOn)
		{
			TblBillChargingMode item = new TblBillChargingMode();
			
				item.BillChargingModeID = varBillChargingModeID;
			
				item.BillChargingModeName = varBillChargingModeName;
			
				item.BillChargingModeCode = varBillChargingModeCode;
			
				item.IsActive = varIsActive;
			
				item.CreatedOn = varCreatedOn;
			
				item.ModifiedOn = varModifiedOn;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn BillChargingModeIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn BillChargingModeNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn BillChargingModeCodeColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn IsActiveColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedOnColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn ModifiedOnColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string BillChargingModeID = @"BillChargingModeID";
			 public static string BillChargingModeName = @"BillChargingModeName";
			 public static string BillChargingModeCode = @"BillChargingModeCode";
			 public static string IsActive = @"IsActive";
			 public static string CreatedOn = @"CreatedOn";
			 public static string ModifiedOn = @"ModifiedOn";
						
		}
		#endregion
		
		#region Update PK Collections
		
        public void SetPKValues()
        {
}
        #endregion
    
        #region Deep Save
		
        public void DeepSave()
        {
            Save();
            
}
        #endregion
	}
}
