using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SmartCBSDataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblChargestype class.
	/// </summary>
    [Serializable]
	public partial class TblChargestypeCollection : ActiveList<TblChargestype, TblChargestypeCollection>
	{	   
		public TblChargestypeCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblChargestypeCollection</returns>
		public TblChargestypeCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblChargestype o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblChargestype table.
	/// </summary>
	[Serializable]
	public partial class TblChargestype : ActiveRecord<TblChargestype>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblChargestype()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblChargestype(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblChargestype(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblChargestype(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblChargestype", TableType.Table, DataService.GetInstance("PrimaryProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarChargesTypeId = new TableSchema.TableColumn(schema);
				colvarChargesTypeId.ColumnName = "ChargesTypeId";
				colvarChargesTypeId.DataType = DbType.Int32;
				colvarChargesTypeId.MaxLength = 0;
				colvarChargesTypeId.AutoIncrement = true;
				colvarChargesTypeId.IsNullable = false;
				colvarChargesTypeId.IsPrimaryKey = true;
				colvarChargesTypeId.IsForeignKey = false;
				colvarChargesTypeId.IsReadOnly = false;
				colvarChargesTypeId.DefaultSetting = @"";
				colvarChargesTypeId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarChargesTypeId);
				
				TableSchema.TableColumn colvarChargesTypeName = new TableSchema.TableColumn(schema);
				colvarChargesTypeName.ColumnName = "ChargesTypeName";
				colvarChargesTypeName.DataType = DbType.AnsiString;
				colvarChargesTypeName.MaxLength = 50;
				colvarChargesTypeName.AutoIncrement = false;
				colvarChargesTypeName.IsNullable = true;
				colvarChargesTypeName.IsPrimaryKey = false;
				colvarChargesTypeName.IsForeignKey = false;
				colvarChargesTypeName.IsReadOnly = false;
				colvarChargesTypeName.DefaultSetting = @"";
				colvarChargesTypeName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarChargesTypeName);
				
				TableSchema.TableColumn colvarIsTax = new TableSchema.TableColumn(schema);
				colvarIsTax.ColumnName = "IsTax";
				colvarIsTax.DataType = DbType.Boolean;
				colvarIsTax.MaxLength = 0;
				colvarIsTax.AutoIncrement = false;
				colvarIsTax.IsNullable = true;
				colvarIsTax.IsPrimaryKey = false;
				colvarIsTax.IsForeignKey = false;
				colvarIsTax.IsReadOnly = false;
				colvarIsTax.DefaultSetting = @"";
				colvarIsTax.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIsTax);
				
				TableSchema.TableColumn colvarCreatedOn = new TableSchema.TableColumn(schema);
				colvarCreatedOn.ColumnName = "CreatedOn";
				colvarCreatedOn.DataType = DbType.DateTime;
				colvarCreatedOn.MaxLength = 0;
				colvarCreatedOn.AutoIncrement = false;
				colvarCreatedOn.IsNullable = true;
				colvarCreatedOn.IsPrimaryKey = false;
				colvarCreatedOn.IsForeignKey = false;
				colvarCreatedOn.IsReadOnly = false;
				colvarCreatedOn.DefaultSetting = @"";
				colvarCreatedOn.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCreatedOn);
				
				TableSchema.TableColumn colvarModifiedOn = new TableSchema.TableColumn(schema);
				colvarModifiedOn.ColumnName = "ModifiedOn";
				colvarModifiedOn.DataType = DbType.DateTime;
				colvarModifiedOn.MaxLength = 0;
				colvarModifiedOn.AutoIncrement = false;
				colvarModifiedOn.IsNullable = true;
				colvarModifiedOn.IsPrimaryKey = false;
				colvarModifiedOn.IsForeignKey = false;
				colvarModifiedOn.IsReadOnly = false;
				colvarModifiedOn.DefaultSetting = @"";
				colvarModifiedOn.ForeignKeyTableName = "";
				schema.Columns.Add(colvarModifiedOn);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["PrimaryProvider"].AddSchema("TblChargestype",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("ChargesTypeId")]
		[Bindable(true)]
		public int ChargesTypeId 
		{
			get { return GetColumnValue<int>(Columns.ChargesTypeId); }
			set { SetColumnValue(Columns.ChargesTypeId, value); }
		}
		  
		[XmlAttribute("ChargesTypeName")]
		[Bindable(true)]
		public string ChargesTypeName 
		{
			get { return GetColumnValue<string>(Columns.ChargesTypeName); }
			set { SetColumnValue(Columns.ChargesTypeName, value); }
		}
		  
		[XmlAttribute("IsTax")]
		[Bindable(true)]
		public bool? IsTax 
		{
			get { return GetColumnValue<bool?>(Columns.IsTax); }
			set { SetColumnValue(Columns.IsTax, value); }
		}
		  
		[XmlAttribute("CreatedOn")]
		[Bindable(true)]
		public DateTime? CreatedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.CreatedOn); }
			set { SetColumnValue(Columns.CreatedOn, value); }
		}
		  
		[XmlAttribute("ModifiedOn")]
		[Bindable(true)]
		public DateTime? ModifiedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.ModifiedOn); }
			set { SetColumnValue(Columns.ModifiedOn, value); }
		}
		
		#endregion
		
		
		#region PrimaryKey Methods		
		
        protected override void SetPrimaryKey(object oValue)
        {
            base.SetPrimaryKey(oValue);
            
            SetPKValues();
        }
        
		
		public SmartCBSDataAccess.TblChargeCollection TblCharges()
		{
			return new SmartCBSDataAccess.TblChargeCollection().Where(TblCharge.Columns.ChargesTypeID, ChargesTypeId).Load();
		}
		#endregion
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varChargesTypeName,bool? varIsTax,DateTime? varCreatedOn,DateTime? varModifiedOn)
		{
			TblChargestype item = new TblChargestype();
			
			item.ChargesTypeName = varChargesTypeName;
			
			item.IsTax = varIsTax;
			
			item.CreatedOn = varCreatedOn;
			
			item.ModifiedOn = varModifiedOn;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varChargesTypeId,string varChargesTypeName,bool? varIsTax,DateTime? varCreatedOn,DateTime? varModifiedOn)
		{
			TblChargestype item = new TblChargestype();
			
				item.ChargesTypeId = varChargesTypeId;
			
				item.ChargesTypeName = varChargesTypeName;
			
				item.IsTax = varIsTax;
			
				item.CreatedOn = varCreatedOn;
			
				item.ModifiedOn = varModifiedOn;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn ChargesTypeIdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ChargesTypeNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn IsTaxColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedOnColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn ModifiedOnColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string ChargesTypeId = @"ChargesTypeId";
			 public static string ChargesTypeName = @"ChargesTypeName";
			 public static string IsTax = @"IsTax";
			 public static string CreatedOn = @"CreatedOn";
			 public static string ModifiedOn = @"ModifiedOn";
						
		}
		#endregion
		
		#region Update PK Collections
		
        public void SetPKValues()
        {
}
        #endregion
    
        #region Deep Save
		
        public void DeepSave()
        {
            Save();
            
}
        #endregion
	}
}
