using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SmartCBSDataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblConsumerStatus class.
	/// </summary>
    [Serializable]
	public partial class TblConsumerStatusCollection : ActiveList<TblConsumerStatus, TblConsumerStatusCollection>
	{	   
		public TblConsumerStatusCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblConsumerStatusCollection</returns>
		public TblConsumerStatusCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblConsumerStatus o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblConsumerStatus table.
	/// </summary>
	[Serializable]
	public partial class TblConsumerStatus : ActiveRecord<TblConsumerStatus>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblConsumerStatus()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblConsumerStatus(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblConsumerStatus(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblConsumerStatus(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblConsumerStatus", TableType.Table, DataService.GetInstance("PrimaryProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarConsumerStatusID = new TableSchema.TableColumn(schema);
				colvarConsumerStatusID.ColumnName = "ConsumerStatusID";
				colvarConsumerStatusID.DataType = DbType.Int32;
				colvarConsumerStatusID.MaxLength = 0;
				colvarConsumerStatusID.AutoIncrement = true;
				colvarConsumerStatusID.IsNullable = false;
				colvarConsumerStatusID.IsPrimaryKey = true;
				colvarConsumerStatusID.IsForeignKey = false;
				colvarConsumerStatusID.IsReadOnly = false;
				colvarConsumerStatusID.DefaultSetting = @"";
				colvarConsumerStatusID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarConsumerStatusID);
				
				TableSchema.TableColumn colvarConsumerStatusName = new TableSchema.TableColumn(schema);
				colvarConsumerStatusName.ColumnName = "ConsumerStatusName";
				colvarConsumerStatusName.DataType = DbType.AnsiString;
				colvarConsumerStatusName.MaxLength = 50;
				colvarConsumerStatusName.AutoIncrement = false;
				colvarConsumerStatusName.IsNullable = true;
				colvarConsumerStatusName.IsPrimaryKey = false;
				colvarConsumerStatusName.IsForeignKey = false;
				colvarConsumerStatusName.IsReadOnly = false;
				colvarConsumerStatusName.DefaultSetting = @"";
				colvarConsumerStatusName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarConsumerStatusName);
				
				TableSchema.TableColumn colvarCreatedOn = new TableSchema.TableColumn(schema);
				colvarCreatedOn.ColumnName = "CreatedOn";
				colvarCreatedOn.DataType = DbType.DateTime;
				colvarCreatedOn.MaxLength = 0;
				colvarCreatedOn.AutoIncrement = false;
				colvarCreatedOn.IsNullable = true;
				colvarCreatedOn.IsPrimaryKey = false;
				colvarCreatedOn.IsForeignKey = false;
				colvarCreatedOn.IsReadOnly = false;
				colvarCreatedOn.DefaultSetting = @"";
				colvarCreatedOn.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCreatedOn);
				
				TableSchema.TableColumn colvarModifiedOn = new TableSchema.TableColumn(schema);
				colvarModifiedOn.ColumnName = "ModifiedOn";
				colvarModifiedOn.DataType = DbType.DateTime;
				colvarModifiedOn.MaxLength = 0;
				colvarModifiedOn.AutoIncrement = false;
				colvarModifiedOn.IsNullable = true;
				colvarModifiedOn.IsPrimaryKey = false;
				colvarModifiedOn.IsForeignKey = false;
				colvarModifiedOn.IsReadOnly = false;
				colvarModifiedOn.DefaultSetting = @"";
				colvarModifiedOn.ForeignKeyTableName = "";
				schema.Columns.Add(colvarModifiedOn);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["PrimaryProvider"].AddSchema("TblConsumerStatus",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("ConsumerStatusID")]
		[Bindable(true)]
		public int ConsumerStatusID 
		{
			get { return GetColumnValue<int>(Columns.ConsumerStatusID); }
			set { SetColumnValue(Columns.ConsumerStatusID, value); }
		}
		  
		[XmlAttribute("ConsumerStatusName")]
		[Bindable(true)]
		public string ConsumerStatusName 
		{
			get { return GetColumnValue<string>(Columns.ConsumerStatusName); }
			set { SetColumnValue(Columns.ConsumerStatusName, value); }
		}
		  
		[XmlAttribute("CreatedOn")]
		[Bindable(true)]
		public DateTime? CreatedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.CreatedOn); }
			set { SetColumnValue(Columns.CreatedOn, value); }
		}
		  
		[XmlAttribute("ModifiedOn")]
		[Bindable(true)]
		public DateTime? ModifiedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.ModifiedOn); }
			set { SetColumnValue(Columns.ModifiedOn, value); }
		}
		
		#endregion
		
		
		#region PrimaryKey Methods		
		
        protected override void SetPrimaryKey(object oValue)
        {
            base.SetPrimaryKey(oValue);
            
            SetPKValues();
        }
        
		
		public SmartCBSDataAccess.TblConsumerCollection TblConsumerRecords()
		{
			return new SmartCBSDataAccess.TblConsumerCollection().Where(TblConsumer.Columns.ConsumerStatusID, ConsumerStatusID).Load();
		}
		#endregion
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varConsumerStatusName,DateTime? varCreatedOn,DateTime? varModifiedOn)
		{
			TblConsumerStatus item = new TblConsumerStatus();
			
			item.ConsumerStatusName = varConsumerStatusName;
			
			item.CreatedOn = varCreatedOn;
			
			item.ModifiedOn = varModifiedOn;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varConsumerStatusID,string varConsumerStatusName,DateTime? varCreatedOn,DateTime? varModifiedOn)
		{
			TblConsumerStatus item = new TblConsumerStatus();
			
				item.ConsumerStatusID = varConsumerStatusID;
			
				item.ConsumerStatusName = varConsumerStatusName;
			
				item.CreatedOn = varCreatedOn;
			
				item.ModifiedOn = varModifiedOn;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn ConsumerStatusIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ConsumerStatusNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedOnColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn ModifiedOnColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string ConsumerStatusID = @"ConsumerStatusID";
			 public static string ConsumerStatusName = @"ConsumerStatusName";
			 public static string CreatedOn = @"CreatedOn";
			 public static string ModifiedOn = @"ModifiedOn";
						
		}
		#endregion
		
		#region Update PK Collections
		
        public void SetPKValues()
        {
}
        #endregion
    
        #region Deep Save
		
        public void DeepSave()
        {
            Save();
            
}
        #endregion
	}
}
