using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SmartCBSDataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblFeedBackStatus class.
	/// </summary>
    [Serializable]
	public partial class TblFeedBackStatusCollection : ActiveList<TblFeedBackStatus, TblFeedBackStatusCollection>
	{	   
		public TblFeedBackStatusCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblFeedBackStatusCollection</returns>
		public TblFeedBackStatusCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblFeedBackStatus o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblFeedBackStatus table.
	/// </summary>
	[Serializable]
	public partial class TblFeedBackStatus : ActiveRecord<TblFeedBackStatus>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblFeedBackStatus()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblFeedBackStatus(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblFeedBackStatus(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblFeedBackStatus(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblFeedBackStatus", TableType.Table, DataService.GetInstance("PrimaryProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarFedbackStatusID = new TableSchema.TableColumn(schema);
				colvarFedbackStatusID.ColumnName = "FedbackStatusID";
				colvarFedbackStatusID.DataType = DbType.Int32;
				colvarFedbackStatusID.MaxLength = 0;
				colvarFedbackStatusID.AutoIncrement = true;
				colvarFedbackStatusID.IsNullable = false;
				colvarFedbackStatusID.IsPrimaryKey = true;
				colvarFedbackStatusID.IsForeignKey = false;
				colvarFedbackStatusID.IsReadOnly = false;
				colvarFedbackStatusID.DefaultSetting = @"";
				colvarFedbackStatusID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarFedbackStatusID);
				
				TableSchema.TableColumn colvarStatusName = new TableSchema.TableColumn(schema);
				colvarStatusName.ColumnName = "StatusName";
				colvarStatusName.DataType = DbType.AnsiString;
				colvarStatusName.MaxLength = 50;
				colvarStatusName.AutoIncrement = false;
				colvarStatusName.IsNullable = true;
				colvarStatusName.IsPrimaryKey = false;
				colvarStatusName.IsForeignKey = false;
				colvarStatusName.IsReadOnly = false;
				colvarStatusName.DefaultSetting = @"";
				colvarStatusName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarStatusName);
				
				TableSchema.TableColumn colvarIsActive = new TableSchema.TableColumn(schema);
				colvarIsActive.ColumnName = "IsActive";
				colvarIsActive.DataType = DbType.Boolean;
				colvarIsActive.MaxLength = 0;
				colvarIsActive.AutoIncrement = false;
				colvarIsActive.IsNullable = true;
				colvarIsActive.IsPrimaryKey = false;
				colvarIsActive.IsForeignKey = false;
				colvarIsActive.IsReadOnly = false;
				colvarIsActive.DefaultSetting = @"";
				colvarIsActive.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIsActive);
				
				TableSchema.TableColumn colvarCreatedOn = new TableSchema.TableColumn(schema);
				colvarCreatedOn.ColumnName = "CreatedOn";
				colvarCreatedOn.DataType = DbType.DateTime;
				colvarCreatedOn.MaxLength = 0;
				colvarCreatedOn.AutoIncrement = false;
				colvarCreatedOn.IsNullable = true;
				colvarCreatedOn.IsPrimaryKey = false;
				colvarCreatedOn.IsForeignKey = false;
				colvarCreatedOn.IsReadOnly = false;
				colvarCreatedOn.DefaultSetting = @"";
				colvarCreatedOn.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCreatedOn);
				
				TableSchema.TableColumn colvarModifiedOn = new TableSchema.TableColumn(schema);
				colvarModifiedOn.ColumnName = "ModifiedOn";
				colvarModifiedOn.DataType = DbType.DateTime;
				colvarModifiedOn.MaxLength = 0;
				colvarModifiedOn.AutoIncrement = false;
				colvarModifiedOn.IsNullable = true;
				colvarModifiedOn.IsPrimaryKey = false;
				colvarModifiedOn.IsForeignKey = false;
				colvarModifiedOn.IsReadOnly = false;
				colvarModifiedOn.DefaultSetting = @"";
				colvarModifiedOn.ForeignKeyTableName = "";
				schema.Columns.Add(colvarModifiedOn);
				
				TableSchema.TableColumn colvarHashCode = new TableSchema.TableColumn(schema);
				colvarHashCode.ColumnName = "HashCode";
				colvarHashCode.DataType = DbType.AnsiString;
				colvarHashCode.MaxLength = 50;
				colvarHashCode.AutoIncrement = false;
				colvarHashCode.IsNullable = true;
				colvarHashCode.IsPrimaryKey = false;
				colvarHashCode.IsForeignKey = false;
				colvarHashCode.IsReadOnly = false;
				colvarHashCode.DefaultSetting = @"";
				colvarHashCode.ForeignKeyTableName = "";
				schema.Columns.Add(colvarHashCode);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["PrimaryProvider"].AddSchema("TblFeedBackStatus",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("FedbackStatusID")]
		[Bindable(true)]
		public int FedbackStatusID 
		{
			get { return GetColumnValue<int>(Columns.FedbackStatusID); }
			set { SetColumnValue(Columns.FedbackStatusID, value); }
		}
		  
		[XmlAttribute("StatusName")]
		[Bindable(true)]
		public string StatusName 
		{
			get { return GetColumnValue<string>(Columns.StatusName); }
			set { SetColumnValue(Columns.StatusName, value); }
		}
		  
		[XmlAttribute("IsActive")]
		[Bindable(true)]
		public bool? IsActive 
		{
			get { return GetColumnValue<bool?>(Columns.IsActive); }
			set { SetColumnValue(Columns.IsActive, value); }
		}
		  
		[XmlAttribute("CreatedOn")]
		[Bindable(true)]
		public DateTime? CreatedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.CreatedOn); }
			set { SetColumnValue(Columns.CreatedOn, value); }
		}
		  
		[XmlAttribute("ModifiedOn")]
		[Bindable(true)]
		public DateTime? ModifiedOn 
		{
			get { return GetColumnValue<DateTime?>(Columns.ModifiedOn); }
			set { SetColumnValue(Columns.ModifiedOn, value); }
		}
		  
		[XmlAttribute("HashCode")]
		[Bindable(true)]
		public string HashCode 
		{
			get { return GetColumnValue<string>(Columns.HashCode); }
			set { SetColumnValue(Columns.HashCode, value); }
		}
		
		#endregion
		
		
		#region PrimaryKey Methods		
		
        protected override void SetPrimaryKey(object oValue)
        {
            base.SetPrimaryKey(oValue);
            
            SetPKValues();
        }
        
		
		public SmartCBSDataAccess.TblMeterFeedBackCollection TblMeterFeedBackRecords()
		{
			return new SmartCBSDataAccess.TblMeterFeedBackCollection().Where(TblMeterFeedBack.Columns.FeedBackStatusID, FedbackStatusID).Load();
		}
		#endregion
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varStatusName,bool? varIsActive,DateTime? varCreatedOn,DateTime? varModifiedOn,string varHashCode)
		{
			TblFeedBackStatus item = new TblFeedBackStatus();
			
			item.StatusName = varStatusName;
			
			item.IsActive = varIsActive;
			
			item.CreatedOn = varCreatedOn;
			
			item.ModifiedOn = varModifiedOn;
			
			item.HashCode = varHashCode;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varFedbackStatusID,string varStatusName,bool? varIsActive,DateTime? varCreatedOn,DateTime? varModifiedOn,string varHashCode)
		{
			TblFeedBackStatus item = new TblFeedBackStatus();
			
				item.FedbackStatusID = varFedbackStatusID;
			
				item.StatusName = varStatusName;
			
				item.IsActive = varIsActive;
			
				item.CreatedOn = varCreatedOn;
			
				item.ModifiedOn = varModifiedOn;
			
				item.HashCode = varHashCode;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn FedbackStatusIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn StatusNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn IsActiveColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedOnColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn ModifiedOnColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn HashCodeColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string FedbackStatusID = @"FedbackStatusID";
			 public static string StatusName = @"StatusName";
			 public static string IsActive = @"IsActive";
			 public static string CreatedOn = @"CreatedOn";
			 public static string ModifiedOn = @"ModifiedOn";
			 public static string HashCode = @"HashCode";
						
		}
		#endregion
		
		#region Update PK Collections
		
        public void SetPKValues()
        {
}
        #endregion
    
        #region Deep Save
		
        public void DeepSave()
        {
            Save();
            
}
        #endregion
	}
}
