using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SmartCBSDataAccess
{
    /// <summary>
    /// Controller class for TblMeterReplacement
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblMeterReplacementController
    {
        // Preload our schema..
        TblMeterReplacement thisSchemaLoad = new TblMeterReplacement();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblMeterReplacementCollection FetchAll()
        {
            TblMeterReplacementCollection coll = new TblMeterReplacementCollection();
            Query qry = new Query(TblMeterReplacement.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblMeterReplacementCollection FetchByID(object ReplaceID)
        {
            TblMeterReplacementCollection coll = new TblMeterReplacementCollection().Where("ReplaceID", ReplaceID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblMeterReplacementCollection FetchByQuery(Query qry)
        {
            TblMeterReplacementCollection coll = new TblMeterReplacementCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ReplaceID)
        {
            return (TblMeterReplacement.Delete(ReplaceID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ReplaceID)
        {
            return (TblMeterReplacement.Destroy(ReplaceID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? IssueID,int? MeterID,DateTime? ModifiedOn,DateTime? CreatedOn,DateTime? ReplacementDate,bool? IsApproved,int? ReplacedBy,int? ApprovedBy,DateTime? ApprovedDate,int? PreviousMeterID,int? ConsumerID,string Remarks,int? PreviousReading,int? CurrentReading)
	    {
		    TblMeterReplacement item = new TblMeterReplacement();
		    
            item.IssueID = IssueID;
            
            item.MeterID = MeterID;
            
            item.ModifiedOn = ModifiedOn;
            
            item.CreatedOn = CreatedOn;
            
            item.ReplacementDate = ReplacementDate;
            
            item.IsApproved = IsApproved;
            
            item.ReplacedBy = ReplacedBy;
            
            item.ApprovedBy = ApprovedBy;
            
            item.ApprovedDate = ApprovedDate;
            
            item.PreviousMeterID = PreviousMeterID;
            
            item.ConsumerID = ConsumerID;
            
            item.Remarks = Remarks;
            
            item.PreviousReading = PreviousReading;
            
            item.CurrentReading = CurrentReading;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int ReplaceID,int? IssueID,int? MeterID,DateTime? ModifiedOn,DateTime? CreatedOn,DateTime? ReplacementDate,bool? IsApproved,int? ReplacedBy,int? ApprovedBy,DateTime? ApprovedDate,int? PreviousMeterID,int? ConsumerID,string Remarks,int? PreviousReading,int? CurrentReading)
	    {
		    TblMeterReplacement item = new TblMeterReplacement();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.ReplaceID = ReplaceID;
				
			item.IssueID = IssueID;
				
			item.MeterID = MeterID;
				
			item.ModifiedOn = ModifiedOn;
				
			item.CreatedOn = CreatedOn;
				
			item.ReplacementDate = ReplacementDate;
				
			item.IsApproved = IsApproved;
				
			item.ReplacedBy = ReplacedBy;
				
			item.ApprovedBy = ApprovedBy;
				
			item.ApprovedDate = ApprovedDate;
				
			item.PreviousMeterID = PreviousMeterID;
				
			item.ConsumerID = ConsumerID;
				
			item.Remarks = Remarks;
				
			item.PreviousReading = PreviousReading;
				
			item.CurrentReading = CurrentReading;
				
	        item.Save(UserName);
	    }
    }
}
