using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SmartCBSDataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblPreferenceApproval class.
	/// </summary>
    [Serializable]
	public partial class TblPreferenceApprovalCollection : ActiveList<TblPreferenceApproval, TblPreferenceApprovalCollection>
	{	   
		public TblPreferenceApprovalCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblPreferenceApprovalCollection</returns>
		public TblPreferenceApprovalCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblPreferenceApproval o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the tblPreferenceApproval table.
	/// </summary>
	[Serializable]
	public partial class TblPreferenceApproval : ActiveRecord<TblPreferenceApproval>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblPreferenceApproval()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblPreferenceApproval(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblPreferenceApproval(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblPreferenceApproval(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("tblPreferenceApproval", TableType.Table, DataService.GetInstance("PrimaryProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarPreferenceApprovlID = new TableSchema.TableColumn(schema);
				colvarPreferenceApprovlID.ColumnName = "PreferenceApprovlID";
				colvarPreferenceApprovlID.DataType = DbType.Int32;
				colvarPreferenceApprovlID.MaxLength = 0;
				colvarPreferenceApprovlID.AutoIncrement = true;
				colvarPreferenceApprovlID.IsNullable = false;
				colvarPreferenceApprovlID.IsPrimaryKey = true;
				colvarPreferenceApprovlID.IsForeignKey = false;
				colvarPreferenceApprovlID.IsReadOnly = false;
				colvarPreferenceApprovlID.DefaultSetting = @"";
				colvarPreferenceApprovlID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPreferenceApprovlID);
				
				TableSchema.TableColumn colvarPreferenceName = new TableSchema.TableColumn(schema);
				colvarPreferenceName.ColumnName = "PreferenceName";
				colvarPreferenceName.DataType = DbType.AnsiString;
				colvarPreferenceName.MaxLength = 50;
				colvarPreferenceName.AutoIncrement = false;
				colvarPreferenceName.IsNullable = true;
				colvarPreferenceName.IsPrimaryKey = false;
				colvarPreferenceName.IsForeignKey = false;
				colvarPreferenceName.IsReadOnly = false;
				colvarPreferenceName.DefaultSetting = @"";
				colvarPreferenceName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPreferenceName);
				
				TableSchema.TableColumn colvarIsApproved = new TableSchema.TableColumn(schema);
				colvarIsApproved.ColumnName = "IsApproved";
				colvarIsApproved.DataType = DbType.Boolean;
				colvarIsApproved.MaxLength = 0;
				colvarIsApproved.AutoIncrement = false;
				colvarIsApproved.IsNullable = true;
				colvarIsApproved.IsPrimaryKey = false;
				colvarIsApproved.IsForeignKey = false;
				colvarIsApproved.IsReadOnly = false;
				colvarIsApproved.DefaultSetting = @"";
				colvarIsApproved.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIsApproved);
				
				TableSchema.TableColumn colvarUserMenuID = new TableSchema.TableColumn(schema);
				colvarUserMenuID.ColumnName = "UserMenuID";
				colvarUserMenuID.DataType = DbType.Int32;
				colvarUserMenuID.MaxLength = 0;
				colvarUserMenuID.AutoIncrement = false;
				colvarUserMenuID.IsNullable = true;
				colvarUserMenuID.IsPrimaryKey = false;
				colvarUserMenuID.IsForeignKey = false;
				colvarUserMenuID.IsReadOnly = false;
				colvarUserMenuID.DefaultSetting = @"";
				colvarUserMenuID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUserMenuID);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["PrimaryProvider"].AddSchema("tblPreferenceApproval",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("PreferenceApprovlID")]
		[Bindable(true)]
		public int PreferenceApprovlID 
		{
			get { return GetColumnValue<int>(Columns.PreferenceApprovlID); }
			set { SetColumnValue(Columns.PreferenceApprovlID, value); }
		}
		  
		[XmlAttribute("PreferenceName")]
		[Bindable(true)]
		public string PreferenceName 
		{
			get { return GetColumnValue<string>(Columns.PreferenceName); }
			set { SetColumnValue(Columns.PreferenceName, value); }
		}
		  
		[XmlAttribute("IsApproved")]
		[Bindable(true)]
		public bool? IsApproved 
		{
			get { return GetColumnValue<bool?>(Columns.IsApproved); }
			set { SetColumnValue(Columns.IsApproved, value); }
		}
		  
		[XmlAttribute("UserMenuID")]
		[Bindable(true)]
		public int? UserMenuID 
		{
			get { return GetColumnValue<int?>(Columns.UserMenuID); }
			set { SetColumnValue(Columns.UserMenuID, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varPreferenceName,bool? varIsApproved,int? varUserMenuID)
		{
			TblPreferenceApproval item = new TblPreferenceApproval();
			
			item.PreferenceName = varPreferenceName;
			
			item.IsApproved = varIsApproved;
			
			item.UserMenuID = varUserMenuID;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varPreferenceApprovlID,string varPreferenceName,bool? varIsApproved,int? varUserMenuID)
		{
			TblPreferenceApproval item = new TblPreferenceApproval();
			
				item.PreferenceApprovlID = varPreferenceApprovlID;
			
				item.PreferenceName = varPreferenceName;
			
				item.IsApproved = varIsApproved;
			
				item.UserMenuID = varUserMenuID;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn PreferenceApprovlIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn PreferenceNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn IsApprovedColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn UserMenuIDColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string PreferenceApprovlID = @"PreferenceApprovlID";
			 public static string PreferenceName = @"PreferenceName";
			 public static string IsApproved = @"IsApproved";
			 public static string UserMenuID = @"UserMenuID";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
