using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SmartCBSDataAccess
{
    /// <summary>
    /// Controller class for tblPreferenceApproval
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblPreferenceApprovalController
    {
        // Preload our schema..
        TblPreferenceApproval thisSchemaLoad = new TblPreferenceApproval();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblPreferenceApprovalCollection FetchAll()
        {
            TblPreferenceApprovalCollection coll = new TblPreferenceApprovalCollection();
            Query qry = new Query(TblPreferenceApproval.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblPreferenceApprovalCollection FetchByID(object PreferenceApprovlID)
        {
            TblPreferenceApprovalCollection coll = new TblPreferenceApprovalCollection().Where("PreferenceApprovlID", PreferenceApprovlID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblPreferenceApprovalCollection FetchByQuery(Query qry)
        {
            TblPreferenceApprovalCollection coll = new TblPreferenceApprovalCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object PreferenceApprovlID)
        {
            return (TblPreferenceApproval.Delete(PreferenceApprovlID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object PreferenceApprovlID)
        {
            return (TblPreferenceApproval.Destroy(PreferenceApprovlID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string PreferenceName,bool? IsApproved,int? UserMenuID)
	    {
		    TblPreferenceApproval item = new TblPreferenceApproval();
		    
            item.PreferenceName = PreferenceName;
            
            item.IsApproved = IsApproved;
            
            item.UserMenuID = UserMenuID;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int PreferenceApprovlID,string PreferenceName,bool? IsApproved,int? UserMenuID)
	    {
		    TblPreferenceApproval item = new TblPreferenceApproval();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.PreferenceApprovlID = PreferenceApprovlID;
				
			item.PreferenceName = PreferenceName;
				
			item.IsApproved = IsApproved;
				
			item.UserMenuID = UserMenuID;
				
	        item.Save(UserName);
	    }
    }
}
