using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace VisitLogDataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblSystemLogging class.
	/// </summary>
    [Serializable]
	public partial class TblSystemLoggingCollection : ActiveList<TblSystemLogging, TblSystemLoggingCollection>
	{	   
		public TblSystemLoggingCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblSystemLoggingCollection</returns>
		public TblSystemLoggingCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblSystemLogging o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the tblSystemLogging table.
	/// </summary>
	[Serializable]
	public partial class TblSystemLogging : ActiveRecord<TblSystemLogging>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblSystemLogging()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblSystemLogging(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblSystemLogging(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblSystemLogging(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("tblSystemLogging", TableType.Table, DataService.GetInstance("PrimaryProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarSystemLoggingID = new TableSchema.TableColumn(schema);
				colvarSystemLoggingID.ColumnName = "SystemLoggingID";
				colvarSystemLoggingID.DataType = DbType.Int32;
				colvarSystemLoggingID.MaxLength = 0;
				colvarSystemLoggingID.AutoIncrement = true;
				colvarSystemLoggingID.IsNullable = false;
				colvarSystemLoggingID.IsPrimaryKey = true;
				colvarSystemLoggingID.IsForeignKey = false;
				colvarSystemLoggingID.IsReadOnly = false;
				colvarSystemLoggingID.DefaultSetting = @"";
				colvarSystemLoggingID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSystemLoggingID);
				
				TableSchema.TableColumn colvarLogDate = new TableSchema.TableColumn(schema);
				colvarLogDate.ColumnName = "LogDate";
				colvarLogDate.DataType = DbType.DateTime;
				colvarLogDate.MaxLength = 0;
				colvarLogDate.AutoIncrement = false;
				colvarLogDate.IsNullable = true;
				colvarLogDate.IsPrimaryKey = false;
				colvarLogDate.IsForeignKey = false;
				colvarLogDate.IsReadOnly = false;
				colvarLogDate.DefaultSetting = @"";
				colvarLogDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLogDate);
				
				TableSchema.TableColumn colvarUserID = new TableSchema.TableColumn(schema);
				colvarUserID.ColumnName = "UserID";
				colvarUserID.DataType = DbType.Int32;
				colvarUserID.MaxLength = 0;
				colvarUserID.AutoIncrement = false;
				colvarUserID.IsNullable = true;
				colvarUserID.IsPrimaryKey = false;
				colvarUserID.IsForeignKey = true;
				colvarUserID.IsReadOnly = false;
				colvarUserID.DefaultSetting = @"";
				
					colvarUserID.ForeignKeyTableName = "UserLogin";
				schema.Columns.Add(colvarUserID);
				
				TableSchema.TableColumn colvarJSONData = new TableSchema.TableColumn(schema);
				colvarJSONData.ColumnName = "JSONData";
				colvarJSONData.DataType = DbType.AnsiString;
				colvarJSONData.MaxLength = -1;
				colvarJSONData.AutoIncrement = false;
				colvarJSONData.IsNullable = true;
				colvarJSONData.IsPrimaryKey = false;
				colvarJSONData.IsForeignKey = false;
				colvarJSONData.IsReadOnly = false;
				colvarJSONData.DefaultSetting = @"";
				colvarJSONData.ForeignKeyTableName = "";
				schema.Columns.Add(colvarJSONData);
				
				TableSchema.TableColumn colvarRequestURL = new TableSchema.TableColumn(schema);
				colvarRequestURL.ColumnName = "RequestURL";
				colvarRequestURL.DataType = DbType.AnsiString;
				colvarRequestURL.MaxLength = -1;
				colvarRequestURL.AutoIncrement = false;
				colvarRequestURL.IsNullable = true;
				colvarRequestURL.IsPrimaryKey = false;
				colvarRequestURL.IsForeignKey = false;
				colvarRequestURL.IsReadOnly = false;
				colvarRequestURL.DefaultSetting = @"";
				colvarRequestURL.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRequestURL);
				
				TableSchema.TableColumn colvarDevice = new TableSchema.TableColumn(schema);
				colvarDevice.ColumnName = "Device";
				colvarDevice.DataType = DbType.AnsiString;
				colvarDevice.MaxLength = 100;
				colvarDevice.AutoIncrement = false;
				colvarDevice.IsNullable = true;
				colvarDevice.IsPrimaryKey = false;
				colvarDevice.IsForeignKey = false;
				colvarDevice.IsReadOnly = false;
				colvarDevice.DefaultSetting = @"";
				colvarDevice.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDevice);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["PrimaryProvider"].AddSchema("tblSystemLogging",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("SystemLoggingID")]
		[Bindable(true)]
		public int SystemLoggingID 
		{
			get { return GetColumnValue<int>(Columns.SystemLoggingID); }
			set { SetColumnValue(Columns.SystemLoggingID, value); }
		}
		  
		[XmlAttribute("LogDate")]
		[Bindable(true)]
		public DateTime? LogDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.LogDate); }
			set { SetColumnValue(Columns.LogDate, value); }
		}
		  
		[XmlAttribute("UserID")]
		[Bindable(true)]
		public int? UserID 
		{
			get { return GetColumnValue<int?>(Columns.UserID); }
			set { SetColumnValue(Columns.UserID, value); }
		}
		  
		[XmlAttribute("JSONData")]
		[Bindable(true)]
		public string JSONData 
		{
			get { return GetColumnValue<string>(Columns.JSONData); }
			set { SetColumnValue(Columns.JSONData, value); }
		}
		  
		[XmlAttribute("RequestURL")]
		[Bindable(true)]
		public string RequestURL 
		{
			get { return GetColumnValue<string>(Columns.RequestURL); }
			set { SetColumnValue(Columns.RequestURL, value); }
		}
		  
		[XmlAttribute("Device")]
		[Bindable(true)]
		public string Device 
		{
			get { return GetColumnValue<string>(Columns.Device); }
			set { SetColumnValue(Columns.Device, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a UserLogin ActiveRecord object related to this TblSystemLogging
		/// 
		/// </summary>
		public VisitLogDataAccess.UserLogin UserLogin
		{
			get { return VisitLogDataAccess.UserLogin.FetchByID(this.UserID); }
			set { SetColumnValue("UserID", value.UserLoginId); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(DateTime? varLogDate,int? varUserID,string varJSONData,string varRequestURL,string varDevice)
		{
			TblSystemLogging item = new TblSystemLogging();
			
			item.LogDate = varLogDate;
			
			item.UserID = varUserID;
			
			item.JSONData = varJSONData;
			
			item.RequestURL = varRequestURL;
			
			item.Device = varDevice;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varSystemLoggingID,DateTime? varLogDate,int? varUserID,string varJSONData,string varRequestURL,string varDevice)
		{
			TblSystemLogging item = new TblSystemLogging();
			
				item.SystemLoggingID = varSystemLoggingID;
			
				item.LogDate = varLogDate;
			
				item.UserID = varUserID;
			
				item.JSONData = varJSONData;
			
				item.RequestURL = varRequestURL;
			
				item.Device = varDevice;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn SystemLoggingIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn LogDateColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn UserIDColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn JSONDataColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn RequestURLColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn DeviceColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string SystemLoggingID = @"SystemLoggingID";
			 public static string LogDate = @"LogDate";
			 public static string UserID = @"UserID";
			 public static string JSONData = @"JSONData";
			 public static string RequestURL = @"RequestURL";
			 public static string Device = @"Device";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
